### ISSUE TITLE
document requirement of dpath for script/make_data.py

### ISSUE THREAD

**Issue by turbomam** [cidgoh/DataHarmonizer#207]

**Comment by ddooley** [comment]
More info on this, or close it?

**Comment by turbomam** [comment]
Normally I would say "add a requirements section to the README", but your README already has a god flow to it

You could make a one-line `requirements.txt` and assume people know how to use that with `pip install -r`

**Comment by cmrn-rhi** [comment]
Might it be worth making a "Quick Start script/make_data.py" page in the wiki for new users?

**Comment by turbomam** [comment]
> Might it be worth making a "Quick Start script/make_data.py" page in the wiki for new users?

Yeah. I can help with that if I have sufficient permission.

The requirement for `dpath` is **semi**-documented in the `linkml-datastructure`'s `requirements.txt` now

**Comment by ddooley** [comment]
I will close this now.  Our code has changed a bit since make_data.py; now it is called tabular_to_schema.py and is run in a particular schema folder (see https://github.com/cidgoh/DataHarmonizer/wiki/DataHarmonizer-Templates).  Soon a change will be implemented so that people can work on templates independently of a DataHarmonizer source code installation.
