### ISSUE TITLE
master commit 021a2ed works with sheets_and_friends but 8b9f0c6 doesn't

### ISSUE THREAD

**Issue by turbomam** [cidgoh/DataHarmonizer#285]
NMDC uses [sheets_and_friends](https://github.com/microbiomedata/sheets_and_friends) to build a custom LinkML schema based on Google Sheets, and then to make a DataHarmonizer via the `data.tsv`/`data.js` route in the master branch.

_We're preparing to switch to the linkml datastructure branch_

I just updated to commit 8b9f0c6 of the master branch, and the DataHarmonizer built by `make_data.py` was blank. Switching back to commit 021a2ed generated a functional DataHarmonizer.

**Comment by ddooley** [comment]
I checked out 8b9f0c6 and ran python ../../script/make_data.py when in one of the template folders (canada_covid19) and data.js was generated, and main.html seemed to work fine.   This version did split out some of the template code:

    <script src="script/export_utils.js"></script>
    <script src="script/validation.js"></script>
    <script src="script/file_utils.js"></script>
    <script src="script/field_rules.js"></script> 
        
    <script src="script/main.js"></script>

So was it the inclusion of dataharmonizer as an app that failed? If so its probably because export_utils.js etc. now need to be included as well as main.js   If its that make_data.py didn't work somehow, that would be more surprising, but would need an error report to debug.

d.

**Comment by ddooley** [comment]
Is this issue pertinent any more?
