### ISSUE TITLE
JSON Export

### ISSUE THREAD

**Issue by kennethbruskiewicz** [cidgoh/DataHarmonizer#431]
Ensure that data can be exported in JSON format: 

```json
{
    "GRDI_Sample": [ /* list items*/ ],
    "AMR_Test": [ /* list items*/ ]
}
```

Is this for all templates?

**Comment by ddooley** [comment]
And since we can, priming this data to mention the schema and version it conforms to.  In future this can be adapted to include language of content too.

**Comment by ddooley** [comment]
Indeed the "save as" json option is the place that triggers writing of this data structure.
I believe the structure of this would match exactly the Container class of any particular standard - so plural GRDI_Samples etc. with the schema, version, and in_language annotation added since that's the minimum info needed to retrieve appropriate schema.

**Comment by ddooley** [comment]
Resolved in upcoming DH2-i18n-rc1 branch.
