### ISSUE TITLE
Multi-sheet Excel export

### ISSUE THREAD

**Issue by kennethbruskiewicz** [cidgoh/DataHarmonizer#434]
With issue #431 : rework the file saving to allow for multi-sheet Excel file saving.

**Comment by kennethbruskiewicz** [comment]
Will come in with https://github.com/cidgoh/DataHarmonizer/tree/dh2-431-export-as-json as I can reuse the same code.

@ddooley the "Save as..." vs the "Export to..." feature – should this only be supported in the "Save as..." feature?

I mention this because "Export to..." seems to be "owned" by the template repository.

**Comment by ddooley** [comment]
"Export to" involves conversion of a given schema to another, so will always involve a menu of specific target formats to map/convert fields to - each usually saved as tab separated data.  That's why its different from "save as" which is not mapping fields, its just saving schema content with its own slot fields/names/structure.

Export to function currently often involves adding export.js script to fiddle with fields as they are transformed to target.

Indeed templates don't necessarily need an export option and in fact the "Export to" menu may list nothing if there is no export target predefined.

**Comment by ddooley** [comment]
@kennethbruskiewicz I believe this is finished in DH2 beta?  But loading of them needs testing?

**Comment by ddooley** [comment]
Resolved in upcoming DH2-i18n-rc1 branch.
